[build]
base = "frontend"
command = "npm ci && npm run build"
publish = ".next"


[[headers]]
for = "/api/draft-mode/*"
[headers.values]
Access-Control-Allow-Origin = "https://hostscena.sanity.studio"
Access-Control-Allow-Credentials = "true"
Access-Control-Allow-Methods = "GET,OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = ""
Content-Security-Policy = "frame-ancestors 'self' https://hostscena.sanity.studio; connect-src 'self' https://jbwzfx7e.api.sanity.io wss://jbwzfx7e.api.sanity.io"
