// const getMockContent = (text1: string, text2: string, text3?: string, text4?: string) => [
//   {
//     _type: 'block',
//     style: 'normal',
//     children: [{ _type: 'span', text: text1, marks: [] }],
//     markDefs: [],
//   },
//   {
//     _type: 'block',
//     style: 'normal',
//     children: [{ _type: 'span', text: text2, marks: [] }],
//     markDefs: [],
//   },
//
//   {
//     _type: 'block',
//     style: 'normal',
//     children: [{ _type: 'span', text: text3, marks: [] }],
//     markDefs: [],
//   },
//
//   {
//     _type: 'block',
//     style: 'normal',
//     children: [{ _type: 'span', text: text4, marks: [] }],
//     markDefs: [],
//   },
// ]
//
// const rawEvents = [
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde01.jpg',
//     title: 'TITTEL',
//     performer: 'Person/produksjon',
//     date: '2025-09-24',
//     startTime: '12:00',
//     endTime: '13:00',
//     location: 'Sted',
//     tag: 'Dans',
//     link: '/',
//     content: getMockContent(
//       'Den italienske koreografen Cristina Rizzo vises for første gang i Norge!',
//       'Hennes forestilling «ULTRAS sleeping dances» er del av festivalens åpningsdag. Høstscena er stolte over å kunne presentere denne koreografen, som har vært en viktig del av italiensk scenekunst siden nittitallet. Med dette tar festivalen skrittet videre for i enda større grad å la samtidsdansen bli del av festivalprogrammet. ULTRAS sleeping dances en hypnotisk reise inn i grenselandet mellom drøm og virkelighet.Med et popkulturelt lydbilde skapes en kontrastfylt atmosfære som forsterker verkets drømmende kvalitet.​ ULTRAS sleeping dances er en opplevelse som inviterer publikum til å reflektere over kroppens rolle i samfunnet. Det er en poetisk og samtidig kraftfull manifestasjon av menneskelig tilstedeværelse og sårbarhet.​',
//       'Cristina Kristal Rizzo er en fremtredende italiensk koreograf og danser basert i Firenze. Hun startet sin profesjonelle karriere i New York, hvor hun utdannet seg ved Martha Graham School of Contemporary Dance og studerte under pionerer som Merce Cunningham og Trisha Brown.​ På 1990-tallet var hun med på å grunnlegge det banebrytende kollektivet Kinkaleri, som fikk internasjonal anerkjennelse for sitt innovative arbeid. Siden 2008 har Rizzo utviklet en selvstendig karriere med fokus på eksperimentell koreografi som kombinerer teoretisk refleksjon med fysisk intensitet.​ Hennes arbeid, inkludert TOCCARE The white dance, VN Serenade og ULTRAS sleeping dances, har blitt vist på prestisjetunge festivaler og institusjoner over hele Europa. Rizzo er også aktiv innen undervisning, foredrag og teoretisk skriving, og hun har skapt koreografier for ledende operahus og museer i Italia og internasjonalt.',
//       'Gå ikke glipp av muligheten til å oppleve dette unike kunstneriske universet hvor dansen sover, drømmer og våkner i deg!',
//     ),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde02.jpg',
//     title: 'POESISCENA',
//     performer: 'Brynjulf Jung Tjønn og Eirik Havnes',
//     date: '2025-09-24',
//     startTime: '08:00',
//     endTime: '13:00',
//     location: 'Baker Walderhaug',
//     tag: 'Litteratur',
//     link: '/',
//     content: getMockContent('Et poetisk møte mellom lyd og ord.', 'Kom og opplev nye uttrykk.'),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde03.jpg',
//     title: 'VARM MELK MED HONNING',
//     performer: 'Dietrichson/Schjoll Frisch',
//     date: '2025-09-24',
//     startTime: '15:00',
//     endTime: '16:00',
//     location: 'Løvenvold Theater',
//     tag: 'Festival',
//     link: '/',
//     content: getMockContent(
//       'En varm forestilling i kald tid.',
//       'Medvirkende byr på ettertanke og energi.',
//     ),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde04.jpg',
//     title: 'WORKSHOP',
//     performer: 'Jens Jeffry Trinidad',
//     date: '2025-09-25',
//     startTime: '11:00',
//     endTime: '12:00',
//     location: 'Ålesund VGS(Fagerlia)',
//     tag: 'musikk',
//     link: '/',
//     content: getMockContent('Lær noe nytt med Jens!', 'Åpent for alle aldre.'),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde05.jpg',
//     title: 'BRANNEN',
//     performer: 'Teatret Vårt',
//     date: '2025-09-25',
//     startTime: '18:00',
//     endTime: '19:00',
//     location: 'Arbeideren Kulturhus',
//     tag: 'Dans',
//     link: '/',
//     content: getMockContent('En historie om tap og mot.', 'Scenekunst med glødende intensitet.'),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde06.jpg',
//     title: 'SHOUT',
//     performer: 'Jens Jeffry Trinidad',
//     date: '2025-09-25',
//     startTime: '20:00',
//     endTime: '21:00',
//     location: 'Sobra scene',
//     tag: 'Dans',
//     link: '/',
//     content: getMockContent('Kraftfullt og rått uttrykk.', 'En kveld du ikke glemmer.'),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde07.jpg',
//     title: 'LANGT UTE OG LENGST INNE',
//     performer: 'Handeland/Berstad/Helgebostad',
//     date: '2025-09-26',
//     startTime: '11:00',
//     endTime: '13:00',
//     location: 'Jugendstilsenteret og Kube kunstmuseum',
//     tag: 'Dans',
//     link: '/',
//     content: getMockContent('En reise gjennom kroppens språk.', 'Performativ kunst i bevegelse.'),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde08.jpg',
//     title: 'VIGGO VENN - ONE MORE TIME TOUR',
//     performer: 'Viggo Venn',
//     date: '2025-09-26',
//     startTime: '19:00',
//     endTime: '20:30',
//     location: 'Parken Kulturhus',
//     tag: 'Dans',
//     link: '/',
//     content: getMockContent('Viggo er tilbake!', 'Show, humor og overraskelser.'),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde09.jpg',
//     title: 'RAVE',
//     performer: 'Skatebård/Kamamuta',
//     date: '2025-09-26',
//     startTime: '22:00',
//     endTime: '02:00',
//     location: 'Arbeideren Kulturhus',
//     tag: 'Dans',
//     link: '/',
//     content: getMockContent('En natt med rytmer og lys.', 'Dans inn i morgentimene.'),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde10.jpg',
//     title: 'PANELSAMTALE "MANNEN RASER"',
//     performer: 'Bjørn Vatne / Simen Velle / Claus Jervell',
//     date: '2025-09-27',
//     startTime: '16:00',
//     endTime: '17:00',
//     location: 'Sted annonseres',
//     tag: 'Dans',
//     link: '/',
//     content: getMockContent('En samtale om menn i krise.', 'Åpent for refleksjon og diskusjon.'),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde11.jpg',
//     title: 'BOKSEGALLA, DRAG & KARAOKE',
//     performer: 'Ålesund bokseklubb/artister/publikum',
//     date: '2025-09-27',
//     startTime: '20:00',
//     endTime: '02:00',
//     location: 'Arbeideren Kulturhus',
//     tag: 'Dans',
//     link: '/',
//     content: getMockContent(
//       'En helaften med alt du ikke visste du trengte.',
//       'Uventede kombinasjoner og energiske innslag.',
//     ),
//   },
//   {
//     image: '/assets/images/snake/Hostscena-bildeslange-bilde12.jpg',
//     title: 'KINO PÅ HØSTSCENA',
//     performer: 'Dag Johan Haugerud',
//     date: '2025-09-28',
//     startTime: '18:00',
//     endTime: '20:00',
//     location: 'Løvenvold Theater',
//     tag: 'Dans',
//     link: '/',
//     content: getMockContent('Filmkveld i teaterets mørke sal.', 'Opplev historier på lerretet.'),
//   },
// ]
//
// // const events: Event[] = rawEvents.map((e) => ({
// //   ...e,
// //   slug: slugify(e.title),
// // }))
//
// // export default events
