import Event from '@/interfaces/event'
import slugify from '@/utils/slugify'

const rawEvents = [
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde01.jpg',
    title: 'TITTEL',
    performer: 'Person/produksjon',
    date: '2025-09-24',
    startTime: '12:00',
    endTime: '13:00',
    location: 'Sted',
    tag: 'Dans',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde02.jpg',
    title: 'POESISCENA',
    performer: 'Brynjulf Jung Tjønn og Eirik Havnes',
    date: '2025-09-24',
    startTime: '08:00',
    endTime: '13:00',
    location: 'Baker Walderhaug',
    tag: 'Litteratur',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde03.jpg',
    title: 'VARM MELK MED HONNING',
    performer: 'Dietrichson/Schjoll Frisch',
    date: '2025-09-24',
    startTime: '15:00',
    endTime: '16:00',
    location: 'Løvenvold Theater',
    tag: 'Festival',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde04.jpg',
    title: 'WORKSHOP',
    performer: 'Jens Jeffry Trinidad',
    date: '2025-09-25',
    startTime: '11:00',
    endTime: '12:00',
    location: 'Ålesund VGS(Fagerlia)',
    tag: 'musikk',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde05.jpg',
    title: 'BRANNEN',
    performer: 'Teatret Vårt',
    date: '2025-09-25',
    startTime: '18:00',
    endTime: '19:00',
    location: 'Arbeideren Kulturhus',
    tag: 'Dans',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde06.jpg',
    title: 'SHOUT',
    performer: 'Jens Jeffry Trinidad',
    date: '2025-09-25',
    startTime: '20:00',
    endTime: '21:00',
    location: 'Sobra scene',
    tag: 'Dans',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde07.jpg',
    title: 'LANGT UTE OG LENGST INNE',
    performer: 'Handeland/Berstad/Helgebostad',
    date: '2025-09-26',
    startTime: '11:00',
    endTime: '13:00',
    location: 'Jugendstilsenteret og Kube kunstmuseum',
    tag: 'Dans',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde08.jpg',
    title: 'VIGGO VENN - ONE MORE TIME TOUR',
    performer: 'Viggo Venn',
    date: '2025-09-26',
    startTime: '19:00',
    endTime: '20:30',
    location: 'Parken Kulturhus',
    tag: 'Dans',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde09.jpg',
    title: 'RAVE',
    performer: 'Skatebård/Kamamuta',
    date: '2025-09-26',
    startTime: '22:00',
    endTime: '02:00',
    location: 'Arbeideren Kulturhus',
    tag: 'Dans',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde10.jpg',
    title: 'PANELSAMTALE "MANNEN RASER"',
    performer: 'Bjørn Vatne / Simen Velle / Claus Jervell',
    date: '2025-09-27',
    startTime: '16:00',
    endTime: '17:00',
    location: 'Sted annonseres',
    tag: 'Dans',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde11.jpg',
    title: 'BOKSEGALLA, DRAG & KARAOKE',
    performer: 'Ålesund bokseklubb/artister/publikum',
    date: '2025-09-27',
    startTime: '20:00',
    endTime: '02:00',
    location: 'Arbeideren Kulturhus',
    tag: 'Dans',
    link: '/',
  },
  {
    image: '/assets/images/snake/Hostscena-bildeslange-bilde12.jpg',
    title: 'KINO PÅ HØSTSCENA',
    performer: 'Dag Johan Haugerud',
    date: '2025-09-28',
    startTime: '18:00',
    endTime: '20:00',
    location: 'Løvenvold Theater',
    tag: 'Dans',
    link: '/',
  },
]

const events: Event[] = rawEvents.map((e) => ({
  ...e,
  slug: slugify(e.title),
}))

export default events
