import News from '@/interfaces/news'

const mockNews: News[] = [
  {
    image: '/assets/images/newsMock/news1.png',
    title: 'PUBLIKUMSVERKTURUS 15 MARS I ÅLESUND',
    tag: 'Arrangement',
    person: 'Høstscena Ensemblet',
    date: '2025-03-15',
    startTime: '18:00',
    endTime: '20:00',
    location: 'Ålesund Kulturhus',
  },
  {
    image: '/assets/images/newsMock/news2.png',
    title: 'FRIVILLIG PÅ HØSTSCENA',
    tag: 'Frivillig',
    person: 'Festivalteam',
    date: '2025-05-10',
    startTime: '17:00',
    endTime: '19:00',
    location: 'Frivilligsentralen',
  },
  {
    image: '/assets/images/newsMock/news3.png',
    title: 'FAGSEMINAR UKE 4 MOLDE',
    tag: 'Fagseminar',
    person: 'Ulike gjester',
    date: '2025-04-05',
    startTime: '10:00',
    endTime: '15:00',
    location: 'Plassen Molde',
  },
  {
    image: '/assets/images/newsMock/news4.png',
    title: 'FESTIVALFILM 2024',
    tag: 'Film',
    person: 'Filmcrew Høstscena',
    date: '2024-12-01',
    startTime: '20:00',
    endTime: '22:00',
    location: 'NF Kino Ålesund',
  },
  {
    image: '/assets/images/newsMock/news5.png',
    title: 'FESTIVALTEASER 2024',
    tag: 'Film',
    person: 'Produksjonsteamet',
    date: '2024-11-15',
    startTime: '12:00',
    endTime: '12:15',
    location: 'Online',
  },
  {
    image: '/assets/images/newsMock/news6.png',
    title: 'BOKSEGALLA',
    tag: 'Litteratur',
    person: 'Forfattere',
    date: '2025-06-01',
    startTime: '19:00',
    endTime: '21:00',
    location: 'Parken Kulturhus',
  },
  {
    image: '/assets/images/newsMock/news1.png',
    title: 'FILMFESTIVAL',
    tag: 'Festival',
    person: 'Norske regissører',
    date: '2025-09-21',
    startTime: '16:00',
    endTime: '23:00',
    location: 'Kulturarena Ålesund',
  },
  {
    image: '/assets/images/newsMock/news2.png',
    title: 'PRESSEKONFERANSE',
    tag: 'Presse',
    person: 'Høstscena',
    date: '2025-01-10',
    startTime: '10:00',
    endTime: '11:00',
    location: 'Høstscena Hovedkontor',
  },
]

export default mockNews
